-- Auto-generated by scripts/backfill-popular-times-playwright.mjs
-- Generated: 2026-04-19T01:51:10.602Z
-- Venues queried: 140

begin;

delete from public.venue_popular_times;

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('7513ec30-ed96-46cf-b5ad-13f0a9477941', 0, 11, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('7513ec30-ed96-46cf-b5ad-13f0a9477941', 0, 11, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('7513ec30-ed96-46cf-b5ad-13f0a9477941', 0, 15, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('7513ec30-ed96-46cf-b5ad-13f0a9477941', 0, 22, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('70ca2134-81e3-4bf5-89ac-4b6cd9e24223', 0, 16, 50, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('70ca2134-81e3-4bf5-89ac-4b6cd9e24223', 0, 16, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('70ca2134-81e3-4bf5-89ac-4b6cd9e24223', 0, 17, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('70ca2134-81e3-4bf5-89ac-4b6cd9e24223', 0, 17, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('0040d258-1945-4340-9009-c04147a1a5cc', 0, 11, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('0040d258-1945-4340-9009-c04147a1a5cc', 0, 11, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('0040d258-1945-4340-9009-c04147a1a5cc', 0, 16, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('a21206d1-cb7c-491a-86c1-90a7d6d77510', 0, 21, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('a21206d1-cb7c-491a-86c1-90a7d6d77510', 0, 21, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('84124c9c-8d93-4e3b-bedf-875252724af5', 0, 21, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('84124c9c-8d93-4e3b-bedf-875252724af5', 0, 21, 50, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('84124c9c-8d93-4e3b-bedf-875252724af5', 0, 21, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('84124c9c-8d93-4e3b-bedf-875252724af5', 0, 23, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('3af25970-cd7b-425f-89cf-c5757fd0aa7e', 0, 21, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('3af25970-cd7b-425f-89cf-c5757fd0aa7e', 0, 21, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('ddbbc73c-2ed1-4dfa-b852-1f666d4065c7', 0, 12, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('ddbbc73c-2ed1-4dfa-b852-1f666d4065c7', 0, 16, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('ddbbc73c-2ed1-4dfa-b852-1f666d4065c7', 0, 20, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('ddbbc73c-2ed1-4dfa-b852-1f666d4065c7', 0, 22, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('ed0a5b2d-ee2c-4210-986b-41aed76f8ceb', 0, 12, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('ed0a5b2d-ee2c-4210-986b-41aed76f8ceb', 0, 19, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('ed0a5b2d-ee2c-4210-986b-41aed76f8ceb', 0, 21, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('6f80d315-f063-4e53-96e0-b7c52d327a6c', 0, 6, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('6f80d315-f063-4e53-96e0-b7c52d327a6c', 0, 6, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('6f80d315-f063-4e53-96e0-b7c52d327a6c', 0, 16, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('c7477007-3b23-4360-b9b6-74906243208d', 0, 12, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('c7477007-3b23-4360-b9b6-74906243208d', 0, 12, 50, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('c7477007-3b23-4360-b9b6-74906243208d', 0, 12, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('c7477007-3b23-4360-b9b6-74906243208d', 0, 13, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('67669c54-945a-4ad9-b324-984d20d7a273', 0, 7, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('67669c54-945a-4ad9-b324-984d20d7a273', 0, 11, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('67669c54-945a-4ad9-b324-984d20d7a273', 0, 11, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('67669c54-945a-4ad9-b324-984d20d7a273', 0, 11, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('99f27c29-e117-48e0-a0b6-07df777725a4', 0, 10, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('99f27c29-e117-48e0-a0b6-07df777725a4', 0, 10, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('99f27c29-e117-48e0-a0b6-07df777725a4', 0, 22, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('68c9c648-45ca-4a58-bc78-2becfefb87ca', 0, 11, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('68c9c648-45ca-4a58-bc78-2becfefb87ca', 0, 11, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('68c9c648-45ca-4a58-bc78-2becfefb87ca', 0, 30, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('894ad864-b73f-4da6-9097-28dd57575f22', 0, 6, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('894ad864-b73f-4da6-9097-28dd57575f22', 0, 7, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('894ad864-b73f-4da6-9097-28dd57575f22', 0, 7, 2, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('500fa2ef-c438-4af1-935f-091452304e1f', 0, 7, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('500fa2ef-c438-4af1-935f-091452304e1f', 0, 7, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('500fa2ef-c438-4af1-935f-091452304e1f', 0, 11, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('b1da76ee-6afb-4f84-a215-cacacdb25110', 0, 12, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('b1da76ee-6afb-4f84-a215-cacacdb25110', 0, 18, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('b1da76ee-6afb-4f84-a215-cacacdb25110', 0, 23, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('232714a5-9ce8-40c4-87f2-3e4e9b826200', 0, 17, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('232714a5-9ce8-40c4-87f2-3e4e9b826200', 0, 19, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('232714a5-9ce8-40c4-87f2-3e4e9b826200', 0, 22, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('674dc438-f7ae-4e9c-9526-70fe0e02cf51', 0, 14, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('674dc438-f7ae-4e9c-9526-70fe0e02cf51', 0, 14, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('674dc438-f7ae-4e9c-9526-70fe0e02cf51', 0, 16, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('674dc438-f7ae-4e9c-9526-70fe0e02cf51', 0, 20, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('a9cad92c-b3ce-43e8-b917-508445566535', 0, 12, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('a9cad92c-b3ce-43e8-b917-508445566535', 0, 12, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('a9cad92c-b3ce-43e8-b917-508445566535', 0, 21, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('b8014412-39d4-4ba8-9a0e-297de1b3f437', 0, 17, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('b8014412-39d4-4ba8-9a0e-297de1b3f437', 0, 17, 50, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('b8014412-39d4-4ba8-9a0e-297de1b3f437', 0, 17, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('b8014412-39d4-4ba8-9a0e-297de1b3f437', 0, 18, 70, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('491add80-d5c2-467e-b37f-0077c0887f6b', 0, 20, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('491add80-d5c2-467e-b37f-0077c0887f6b', 0, 23, 100, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();
insert into public.venue_popular_times (venue_id, weekday, hour, busyness, updated_at) values ('491add80-d5c2-467e-b37f-0077c0887f6b', 0, 23, 22, now()) on conflict (venue_id, weekday, hour) do update set busyness = excluded.busyness, updated_at = now();

-- No popular times extracted for these venues:
-- elsewhere | Elsewhere | Popular times panel not found
-- atrium-bar | Atrium Bar | Popular times panel not found
-- su-casa-gold-coast | Su Casa Gold Coast | Popular times panel not found
-- mambo-gold-coast | Mambo Gold Coast | Popular times panel not found
-- havana-rnb-nightclub | Havana RnB Nightclub | Popular times panel not found
-- desire-nightclub | Desire Nightclub | Popular times panel not found
-- empire-r-b-nightclub | Empire R&B Nightclub | Popular times panel not found
-- tempo-nightclub | Tempo Nightclub | Popular times panel not found
-- retro-s | Retro''s | Popular times panel not found
-- pink-flamingo-spiegelclub | Pink Flamingo Spiegelclub | Popular times panel not found
-- dracula-s | Dracula''s | Popular times panel not found
-- casablanca-gold-coast | Casablanca Gold Coast | Popular times panel not found
-- moxy-s-rooftop-bar | Moxy''s Rooftop Bar | Popular times panel not found
-- aviary-rooftop-bar | Aviary Rooftop Bar | Popular times panel not found
-- sue-o-rooftop | Sueño Rooftop | Popular times panel not found
-- stingray-lounge | Stingray Lounge | Popular times panel not found
-- deck-bar | Deck Bar | Popular times panel not found
-- coast | COAST | Popular times panel not found
-- chapter-verse-bar-and-lounge | Chapter & Verse Bar and Lounge | Popular times panel not found
-- inca-fusion-peruvian-latin-food-gold-coast | Inca Fusion - Peruvian & Latin Food | Popular times panel not found
-- baritalia-surfers-paradise | Baritalia Surfers Paradise | Popular times panel not found
-- roosevelt-lounge | Roosevelt Lounge | Popular times panel not found
-- caracara-cantina-and-tequila-bar | Caracara Cantina And Tequila Bar | Popular times panel not found
-- pearls-bar | Pearls Bar | Popular times panel not found
-- affinity-bar-burleigh | Affinity Bar Burleigh | Popular times panel not found
-- bine-bar-dining | Bine Bar & Dining | Popular times panel not found
-- bon-bon-bar | Bon Bon Bar | Popular times panel not found
-- lars-bar-grill | Lars Bar & Grill | Popular times panel not found
-- the-cambus-wallace | The Cambus Wallace | Popular times panel not found
-- conkabar | ConKaBar | Popular times panel not found
-- lockwood-bar | Lockwood Bar | Popular times panel not found
-- maman-bar-kitchen | Maman Bar & Kitchen | Popular times panel not found
-- paloma-wine-bar | Paloma Wine Bar | Popular times panel not found
-- pink-monkey-bar-grill | Pink Monkey Bar & Grill | Popular times panel not found
-- terronia-cocktail-bar | Terronia Cocktail Bar | Popular times panel not found
-- whisky-lounge | Whisky Lounge | Popular times panel not found
-- bar-11 | Bar 11 | Popular times panel not found
-- carafe-wine | Carafe Wine | Popular times panel not found
-- percy-s-bar | Percy''s Bar | Popular times panel not found
-- double-barrel-kitchen-and-bar | Double Barrel Kitchen and Bar | Popular times panel not found
-- the-vintage-bar-co | The Vintage Bar Co | Popular times panel not found
-- vinnies-dive-bar | VINNIES DIVE BAR | Popular times panel not found
-- den-devine-restaurant-music-lounge | Den Devine Restaurant & Music Lounge | Popular times panel not found
-- fat-freddy-s-beach-bar-and-diner | Fat Freddy''s Beach Bar And Diner | Popular times panel not found
-- garden-kitchen-bar | Garden Kitchen & Bar | Popular times panel not found
-- the-local-tavern | The Local Tavern | Popular times panel not found
-- waxy-s-irish-pub-and-skyline-roof-top-bar | Waxy''s Irish Pub and Skyline Roof Top Bar | Popular times panel not found
-- chevron-tavern | Chevron Tavern | Popular times panel not found
-- surfers-paradise-beergarden | Surfers Paradise Beergarden | Popular times panel not found
-- e-star-karaoke | E Star Karaoke | Popular times panel not found
-- the-bedroom | The Bedroom | Popular times panel not found
-- cali-beach | Cali Beach | Popular times panel not found
-- magic-men | Magic Men | Popular times panel not found
-- mermaid-beach-tavern | Mermaid Beach Tavern | Popular times panel not found
-- ashmore-tavern | Ashmore Tavern | Popular times panel not found
-- ferry-road-tavern | Ferry Road Tavern | Popular times panel not found
-- burleigh-sports-club | Burleigh Sports Club | Popular times panel not found
-- helensvale-tavern | Helensvale Tavern | Popular times panel not found
-- gold-coast-tavern | Gold Coast Tavern | Popular times panel not found
-- dublin-docks-tavern | Dublin Docks Tavern | Popular times panel not found
-- nerang-rsl-memorial-club | Nerang RSL & Memorial Club | Popular times panel not found
-- benowa-tavern | Benowa Tavern | Popular times panel not found
-- southport-sharks-afl-club | Southport Sharks AFL Club | Popular times panel not found
-- parkwood-tavern | Parkwood Tavern | Popular times panel not found
-- suzi-cue-s | Suzi Cue''s | Popular times panel not found
-- d-arcy-arms | D''Arcy Arms | Popular times panel not found
-- steampunk-surfers-paradise | Steampunk Surfers Paradise | Popular times panel not found
-- social-house | Social House | Popular times panel not found
-- shooeys | Shooeys | Popular times panel not found
-- club-paradise | Club Paradise | Popular times panel not found
-- bmg-cowboys | BMG Cowboys | Popular times panel not found
-- woodfired-mediterranean-grill-cafe | Woodfired Mediterranean Grill & Cafe | Popular times panel not found
-- the-spring | The Spring | Popular times panel not found
-- la-playa-beach-and-eats | La Playa Beach and Eats | Popular times panel not found
-- the-cavill-hotel | The Cavill Hotel | Popular times panel not found
-- el-camino-cantina-surfers-paradise | El Camino Cantina Surfers Paradise | Popular times panel not found
-- hyde-paradiso | Hyde Paradiso | Popular times panel not found
-- hotel-jardin | Hotel Jardin | Popular times panel not found
-- finn-mccool-s-surfers-paradise | Finn McCool''s Surfers Paradise | Popular times panel not found
-- down-under-party-tours | Down Under Party Tours | Popular times panel not found
-- wicked-nightlife-tours-club-crawl | Wicked Nightlife Tours - Club Crawl | Popular times panel not found
-- the-collective-palm-beach | The Collective Palm Beach | Popular times panel not found
-- crafty-s | Crafty''s | Popular times panel not found
-- cherry | Cherry | Popular times panel not found
-- miss-moneypenny-s | Miss Moneypenny''s | Popular times panel not found
-- the-loose-moose | The Loose Moose | Popular times panel not found
-- the-lucky-squire | The Lucky Squire | Popular times panel not found
-- apres-surf | Apres Surf | Popular times panel not found
-- burleigh-heads-hotel | Burleigh Heads Hotel | Popular times panel not found
-- club-burleigh | Club Burleigh | Popular times panel not found
-- local-burleigh | Local Burleigh | Popular times panel not found
-- margarita-cartel | Margarita Cartel | Popular times panel not found
-- masu-izakaya | Masu Izakaya | Popular times panel not found
-- na-mi | Naami | Popular times panel not found
-- the-crab-pot | The Crab Pot | Popular times panel not found
-- the-malibu-racquet-club | The Malibu Racquet Club | Popular times panel not found
-- the-tropic-burleigh | The Tropic - Burleigh | Popular times panel not found
-- ze-pickle | Ze Pickle | Popular times panel not found
-- kirra-beach-house | Kirra Beach House | Popular times panel not found
-- the-coolangatta-hotel | The Coolangatta Hotel | Popular times panel not found
-- destino | Destino | Popular times panel not found
-- mano-s-tedder-avenue | Mano''s Tedder Avenue | Popular times panel not found
-- m-re-restaurant-by-la-luna | MĀRE Restaurant by La Luna | Popular times panel not found
-- juju-mermaid-beach | Juju Mermaid Beach | Popular times panel not found
-- loki | Loki | Popular times panel not found
-- lupo | Lupo | Popular times panel not found
-- moustache | Moustache | Popular times panel not found
-- nightcap | Nightcap | Popular times panel not found
-- nobby-s-beach-surf-club | Nobby''s Beach Surf Club | Popular times panel not found
-- nobby-s-rock | Nobby''s Rock | Popular times panel not found
-- the-arc-at-nobby-s | The Arc at Nobby''s | Popular times panel not found
-- whiskey-59 | Whiskey@59 | Popular times panel not found
-- ground-n-sound | Ground N Sound | Popular times panel not found
-- last-night-on-earth | Last Night on Earth | Popular times panel not found
-- sopo | SOPO | Popular times panel not found
-- walk-ins-welcome | Walk-ins Welcome | Popular times panel not found
-- sopo-brewing-co | SOPO Brewing Co. | Popular times panel not found
-- six-tricks-distilling-co | Six-Tricks Distilling Co. | Popular times panel not found
-- madocke-beer-brewing-company | Madocke Beer Brewing Company | Popular times panel not found

commit;
